name: impl-filters
channels:
  - ccpi
  - anaconda
  - astra-toolbox/label/dev
  - conda-forge
  - defaults
dependencies:
  - astra-toolbox=1.9.0.dev10
  - cudatoolkit=10.0.130
  - matplotlib
  - numpy
  - scikit-image=0.16.2
  - scipy=1.4.1
  - tomopy=1.7.0
  - tqdm
